### ISSUE TITLE
Simulated pulse source fails with a map?

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#106]
```
Traceback (most recent call last):
  File "dc.py", line 145, in updateReceived
    self.observeTab.handleTriggerRateMessage(d)
  File "/home/pcuser/dastard-commander/observe.py", line 46, in handleTriggerRateMessage
    self.buildCRM()
  File "/home/pcuser/dastard-commander/observe.py", line 95, in buildCRM
    self.crm_grid = CountRateMap(self, self.cols, self.rows, self.getChannelNames())
  File "/home/pcuser/dastard-commander/observe.py", line 90, in getChannelNames
    assert(len(channel_names) == cols*rows*(1+self.auxPerChan))
AssertionError
Aborted (core dumped)
```

**Comment by joefowler** [comment]
Isn't this a dastard-commander issue?

**Comment by ggggggggg** [comment]
Umm, yes. I'll move it.
