### ISSUE TITLE
Abaco reader crashes if you start it twice

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#142]
#126 is solved by reading of the Abaco shared memory. However, if you stop and re-start the abaco source, dastard does a hard crash:

```text
panic: runtime error: index out of range

goroutine 17269 [running]:
github.com/usnistgov/dastard.(*TriggerBroker).Run(0xc42026c090)
	/home/fowlerj/go/src/github.com/usnistgov/dastard/group_trigger.go:239 +0xbad
created by github.com/usnistgov/dastard.(*AnySource).PrepareRun
	/home/fowlerj/go/src/github.com/usnistgov/dastard/data_source.go:700 +0x125
exit status 2
```

This error occurs even if you run a simulated pulse source between the 2x that you start the Abaco.

**Comment by joefowler** [comment]
Closed with ca5d65e
