### ISSUE TITLE
Abaco reader sometimes crashes with SIGSEGV

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#145]
Not always, but sometimes with the Abaco data source, if you start, stop, and repeat multiple times, you get a hard crash:

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7b2f46]

goroutine 1701 [running]:
github.com/usnistgov/dastard/ringbuffer.(*RingBuffer).ReadAll(0xc4201ece00, 0x8, 0x8, 0xc4201cc300, 0x8, 0x8)
	/home/fowlerj/go/src/github.com/usnistgov/dastard/ringbuffer/ringbuffer.go:231 +0x26
github.com/usnistgov/dastard.(*AbacoSource).readerMainLoop(0xc4201fe000)
	/home/fowlerj/go/src/github.com/usnistgov/dastard/abaco.go:309 +0x2df
created by github.com/usnistgov/dastard.(*AbacoSource).StartRun
	/home/fowlerj/go/src/github.com/usnistgov/dastard/abaco.go:264 +0x66
exit status 2
```

**Comment by joefowler** [comment]
Debugging print statements seemed to make this crash even less frequent. Frustrating! But I made it happen once.  Inside `RingBuffer.ReadAll()` I was able to find that `rb.desc==0x0` was true just before the panic. Which would explain why there's a panic.

**Comment by joefowler** [comment]
It looks like the problem is that `RingBuffer.Open` is completing normally without error, but by the time the regular data sampling loop is running, something has closed the ring:

```text
2019/04/30 11:42:04 Starting data source named ABACOSOURCE
Ring.Open succeeds. desc = 0x7f33c98b6000
Device ring.Open returns no error.
2019/04/30 11:42:04 Abaco bytes read for FindFrameBits: 163840
Raw lastdata: [1 0 192 41 2 0 192 41 4 0 192 41 6 0 192 41 8 0 192 41 10 0 192 41 12 0 192 41 14 0 192 41]
2019/04/30 11:42:04 SEND STATUS dastard.ServerStatus
{"Running":true,"SourceName":"Abaco","Nchannels":8,"Nsamples":400,"Npresamp":100,"Ncol":[],"Nrow":[],"ChannelsWithProjectors":null}
2019/04/30 11:42:04 nextBlock channel was closed; stopping the source normally
2019/04/30 11:42:04 SEND TRIGGER []dastard.FullTriggerState
[{"ChannelIndicies":[0],"AutoTrigger":false,"AutoDelay":1000000000,"LevelTrigger":false,"LevelRising":false,"LevelLevel":4000,"EdgeTrigger":false,"EdgeRising":true,"EdgeFalling":false,"EdgeLevel":100,"EdgeMulti":false,"EdgeMultiNoise":false,"EdgeMultiMakeShortRecords":false,"EdgeMultiMakeContaminatedRecords":false,"EdgeMultiVerifyNMonotone":0},{"ChannelIndicies":[1,2,3,4,5,6,7],"AutoTrigger":false,"AutoDelay":250000000,"LevelTrigger":false,"LevelRising":false,"LevelLevel":4000,"EdgeTrigger":false,"EdgeRising":true,"EdgeFalling":false,"EdgeLevel":100,"EdgeMulti":false,"EdgeMultiNoise":false,"EdgeMultiMakeShortRecords":false,"EdgeMultiMakeContaminatedRecords":false,"EdgeMultiVerifyNMonotone":0}]
RingBuffer.ReadAll with rb.desc=0x0
panic: AbacoDevice.ring.ReadAll failed

goroutine 9393 [running]:
github.com/usnistgov/dastard.(*AbacoSource).readerMainLoop(0xc4201fc000)
	/home/fowlerj/go/src/github.com/usnistgov/dastard/abaco.go:313 +0xaab
created by github.com/usnistgov/dastard.(*AbacoSource).StartRun
```

Notice this part: **2019/04/30 11:42:04 nextBlock channel was closed; stopping the source normally**. That is what I have to track down...

**Comment by joefowler** [comment]
Hmm. Seems like this must be a race condition in which the `AnySource.CoreLoop()` is completing correctly (though I don't know why it's exiting), but the `AbacoSource.readerMainLoop()` is still waking up every 50 ms to read from the ring buffer. By that point, the ring buffer has been closed and is no longer readable.

Unfortunately, I cannot reproduce this error today. I'm not sure why. I'm going to put this aside. We can put the whole issue on hold if I don't see it again.

**Comment by joefowler** [comment]
This issue has not come up in a year. Close it.
