### ISSUE TITLE
zero length matrix panic observed with "two shorter records" setting

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#234]
```panic: mat: zero length in matrix dimension

goroutine 91144342 [running]:
gonum.org/v1/gonum/mat.NewVecDense(...)
	/home/pcuser/go/pkg/mod/gonum.org/v1/gonum@v0.7.0/mat/vector.go:93
github.com/usnistgov/dastard.(*DataStreamProcessor).AnalyzeData(0xc000257800, 0xc0026ae000, 0xc5e, 0x1000)
	/home/pcuser/go/src/github.com/usnistgov/dastard/process_data.go:188 +0x81e
github.com/usnistgov/dastard.(*DataStreamProcessor).processSegment(0xc000257800, 0xc0003b8240)
	/home/pcuser/go/src/github.com/usnistgov/dastard/process_data.go:119 +0xc1
github.com/usnistgov/dastard.(*AnySource).ProcessSegments.func1(0xc00020c6b0, 0xc0003b8240, 0xc000257800)
	/home/pcuser/go/src/github.com/usnistgov/dastard/data_source.go:347 +0x5d
created by github.com/usnistgov/dastard.(*AnySource).ProcessSegments
	/home/pcuser/go/src/github.com/usnistgov/dastard/data_source.go:345 +0xe1
```

**Comment by joefowler** [comment]
This has to do with your fancy big-boy trigger settings, so I figure you are the right person to fix it!
