### ISSUE TITLE
triggering panic while testing with triangles

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#260]
I was trying to test triggering stability using triangle waves from the crate and ran into this while changing triangle parameters. At the time they were 0,6,1 dwell, steps, step size.

```panic: dsp.EdgeMultiVerifyNMonotone 66, dsp.NSamples 128, dsp.NPreSamples 64

goroutine 415274 [running]:
github.com/usnistgov/dastard.(*DataStreamProcessor).edgeMultiTriggerComputeAppend(0xc0000f4480, {0x0, 0x0, 0x0})
	/home/xf07id1/go/src/github.com/usnistgov/dastard/triggering.go:233 +0x1205
github.com/usnistgov/dastard.(*DataStreamProcessor).TriggerData(0xc0000f4480)
	/home/xf07id1/go/src/github.com/usnistgov/dastard/triggering.go:573 +0x4a
github.com/usnistgov/dastard.(*DataStreamProcessor).processSegment(0xc0000f4480, 0xc0004782a0)
	/home/xf07id1/go/src/github.com/usnistgov/dastard/process_data.go:118 +0x46
github.com/usnistgov/dastard.(*AnySource).ProcessSegments.func1(0x47059a8000000080)
	/home/xf07id1/go/src/github.com/usnistgov/dastard/data_source.go:347 +0x58
created by github.com/usnistgov/dastard.(*AnySource).ProcessSegments
	/home/xf07id1/go/src/github.com/usnistgov/dastard/data_source.go:345 +0x93
(qsp) [xf07id1@xf07id-det3 ~]$ 
```

**Comment by joefowler** [comment]
So this is not the `TriangleSource` but a Lancero source where the data are triangles? 

This must be related to #259 #257 #256 and #254 and to our plans for fixing them, because the basic edge multi trigger (EMT) design seems to have unhappy edge cases. We have discussed removing the multi-trigger aspect entirely (still considering).
