### ISSUE TITLE
panic as result of race condition?

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#76]
This happened when I turned down record lengths while triggering.

```
panic: runtime error: slice bounds out of range

goroutine 182 [running]:
github.com/usnistgov/dastard.(*DataStreamProcessor).triggerAtSpecificSamples(0xc420271180, 0xc4202711c8, 0x2b, 0x2c, 0xc8, 0xa)
	/Users/oneilg/go/src/github.com/usnistgov/dastard/triggering.go:63 +0x25b
github.com/usnistgov/dastard.(*DataStreamProcessor).edgeMultiTriggerComputeAppend(0xc420271180, 0x0, 0x0, 0x0, 0xc4201ee1e0, 0x45fb550, 0x9)
	/Users/oneilg/go/src/github.com/usnistgov/dastard/triggering.go:262 +0x72a
github.com/usnistgov/dastard.(*DataStreamProcessor).TriggerData(0xc420271180, 0xc420460ee0, 0xc420271338, 0xc4204f37b8, 0xc4201a0cb8, 0x0, 0x0)
	/Users/oneilg/go/src/github.com/usnistgov/dastard/triggering.go:422 +0x63
github.com/usnistgov/dastard.(*DataStreamProcessor).processSegment(0xc420271180, 0xc420460ee0)
	/Users/oneilg/go/src/github.com/usnistgov/dastard/process_data.go:124 +0xaf
github.com/usnistgov/dastard.(*DataStreamProcessor).ProcessData(0xc420271180, 0xc4201a0c60)
	/Users/oneilg/go/src/github.com/usnistgov/dastard/process_data.go:114 +0xe2
github.com/usnistgov/dastard.(*AnySource).PrepareRun.func1(0xc4201d8028, 0xc420271180, 0xc4201a0c60)
	/Users/oneilg/go/src/github.com/usnistgov/dastard/data_source.go:455 +0xa1
created by github.com/usnistgov/dastard.(*AnySource).PrepareRun
	/Users/oneilg/go/src/github.com/usnistgov/dastard/data_source.go:450 +0x5d7
exit status 2
```

**Comment by ggggggggg** [comment]
Actually this is probably just a bug in EdgeMulti

**Comment by ggggggggg** [comment]
This was a bug in EdgeMulti, fixed in https://github.com/usnistgov/dastard/commit/4eee88bfd522383760aacb076ffb7e868b68276c
