### ISSUE TITLE
dastard crashes upon lancero start

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#90]
2 of 2 times so far

```
2018/07/30 10:17:50 First frame bit at word 16, so release 64 of 10497792 bytes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8e7e8c]

goroutine 8 [running]:
github.com/usnistgov/dastard.(*SourceControl).Start(0xc4201d4f70, 0xc4202f80f0, 0xc4203020a8, 0x0, 0x0)
	/home/pcuser/go/src/github.com/usnistgov/dastard/rpc_server.go:245 +0x1ac
reflect.Value.call(0xc4200328a0, 0xc42000e688, 0x13, 0x9fbdf2, 0x4, 0xc420077e30, 0x3, 0x3, 0x93e500, 0x1, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4200328a0, 0xc42000e688, 0x13, 0xc420077e30, 0x3, 0x3, 0x16, 0x16, 0x16)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc4200837c0, 0xc4200aaa00, 0xc420302078, 0x0, 0xc42015e800, 0xc42011d260, 0x935300, 0xc4202f80f0, 0x16, 0x9292c0, ...)
	/usr/lib/go-1.10/src/net/rpc/server.go:384 +0x14e
net/rpc.(*Server).ServeRequest(0xc4200aaa00, 0xa6cbc0, 0xc420032c00, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/rpc/server.go:504 +0x235
github.com/usnistgov/dastard.RunRPCServer.func2.1(0xa6e720, 0xc42000e6f0, 0xc4200aaa00)
	/home/pcuser/go/src/github.com/usnistgov/dastard/rpc_server.go:535 +0x21f
created by github.com/usnistgov/dastard.RunRPCServer.func2
	/home/pcuser/go/src/github.com/usnistgov/dastard/rpc_server.go:529 +0x210
exit status 2
```

**Comment by ggggggggg** [comment]
I haven't seen this for a long time, closing.
