### ISSUE TITLE
edgeMulti crash

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#92]
Maybe related to the fact that I think we should start at 6+dsp.NSamples

```
panic: runtime error: index out of range

goroutine 8858718 [running]:
github.com/usnistgov/dastard.(*DataStreamProcessor).edgeMultiTriggerComputeAppend(0xc42436e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/pcuser/go/src/github.com/usnistgov/dastard/triggering.go:230 +0xe9e
github.com/usnistgov/dastard.(*DataStreamProcessor).TriggerData(0xc42436e000, 0xc421e177a0, 0xc42436e1c0, 0xa1fb50, 0xc42774cfa0, 0xc42774cf90, 0x430ec9)
	/home/pcuser/go/src/github.com/usnistgov/dastard/triggering.go:548 +0x63
github.com/usnistgov/dastard.(*DataStreamProcessor).processSegment(0xc42436e000, 0xc421e177a0)
	/home/pcuser/go/src/github.com/usnistgov/dastard/process_data.go:133 +0xa9
github.com/usnistgov/dastard.(*AnySource).ProcessSegments.func1(0xc42031c030, 0xc421e177a0, 0xc42436e000)
	/home/pcuser/go/src/github.com/usnistgov/dastard/data_source.go:193 +0x5b
created by github.com/usnistgov/dastard.(*AnySource).ProcessSegments
	/home/pcuser/go/src/github.com/usnistgov/dastard/data_source.go:191 +0xc0
exit status 2
```

**Comment by ggggggggg** [comment]
This is fixed. There is still an occasional edgeMultiCrash, but much less frequency and with a different cause.
